version: 1
project:
  toc:
    - file: book/home.md
    
    - title: 1. Python Programming
      children:
        - pattern: 01_python_programming/*.ipynb 

    - title: 2. Mathematics
      children:
        - file: 02_mathematics/_08_applied_math.ipynb
          hidden: true
        - pattern: 02_mathematics/*.ipynb